### ISSUE TITLE
Fix PermissionIssue on Bukkit

### ISSUE THREAD

**Issue by einrobin** [CloudNetService/CloudNet-v2#104]
To fix the issue that PlotSquared's "plots.plot.X" permission does not work finally that it also works with permissions given by a PermissionGroup and not only the permissions which are given to the player directly  and that Player#getEffectivePermissions returns all permissions of the player and its groups, we should use all permissions of the player its groups in CloudPermissible#getEffectivePermissions.

**Comment by GiantTreeLP** [comment]
It works, as long as the player has no permissions attached to it directly.

That leaves the set empty and the plugins refer to another method.

I will fix that ASAP.

Mit freundlichen Grüßen
Marvin Krüger

________________________________
