### ISSUE TITLE
Fix Tab Color in SimpleNameTags

### ISSUE THREAD

**Issue by florianpreuss** [CloudNetService/CloudNet-v2#114]
Seit MC Version 1.13.2 muss dem Team noch die color gesetzt werden, ansonsten wird der name in der Tablist weiß angezeigt.

**Comment by derklaro** [comment]
Korrekt, die Methode existiert leider erst ab der 1.12, hier müsste man einen Chack hinzufügen

**Comment by GiantTreeLP** [comment]
Wir brauchen wahrscheinlich die Methode: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Bukkit.html#getVersion--

Und dann halt einfach die Methode nutzen, wird ja eh erst zur Laufzeit alles geprüft.

**Comment by derklaro** [comment]
Dann müssen wir mit reflections arbeiten, sollte aber nicht das große Problem sein 🤷‍♂️

**Comment by juliarn** [comment]
Ne, wieso das? Die CloudNet API nutzt die 1.13-Dependency, ein einfacherer check vor dem Aufruf der Methode sollte da reichen.

**Comment by derklaro** [comment]
Nene, die Dependency hast du geupdated du Sack xD

**Comment by juliarn** [comment]
JA DA WAR EIN FALSCHES COMMENT DRAN xD
