### ISSUE TITLE
Verbinden zum Server

### ISSUE THREAD

**Issue by officialPlocki** [CloudNetService/CloudNet-v2#116]
Hallo,
da ich einen Minecraft Server besitze, dachte ich mir, das kann ich gebrauchen, da die Unterserver ständig verwaltet werden mussten und ständig abstürzten.
Cloudnet ließ sich installieren, aber als ich den Server betreten wollte zeigte mir Minecraft an, das der Server offline wäre. Ich habe schon den normalen Minecraft Port ,,25565'' ausprobiert sowie über die Zahlen Ip. Geht leider auch nicht.

Mfg

**Comment by Sarsum** [comment]
Moin, 
Als erstes müssten wir wissen ob du CloudNet V2 oder V3 nutzt, bisher ist nur V2 hier auf GitHub.

Desweiteren würde ich dich gerne auf unseren Support-Discord hinweisen: https://discord.gg/CPCWr7w da oft die Kommunikation dort einfacher ist.

Viel Grüße

**Comment by officialPlocki** [comment]
V3

**Comment by GiantTreeLP** [comment]
Support für die V3 gibt es ausschließlich auf spigotmc.org oder Discord.
