### ISSUE TITLE
CloudNet 3.0

### ISSUE THREAD

**Issue by sando123** [CloudNetService/CloudNet-v2#134]
Ich möchte das MOTD eines Services ändern aber wenn ich es Speichere kommt auf dem MOTD ein komisches  A mit ner Line oben drauf kann wer Helfen?

**Comment by GiantTreeLP** [comment]
Support für die v3 gibt es nur auf Discord.
Das hier ist das Repository für den Code der v2.

https://discord.gg/CPCWr7w
