### ISSUE TITLE
CloudNet2 /cloudserver Befehl

### ISSUE THREAD

**Issue by peter81745** [CloudNetService/CloudNet-v2#147]
wenn ich auf meinen Server ingame /cloudserver eingebe passiert nichts.

**Comment by juliarn** [comment]
Hallo, welchen GroupMode hat denn die Gruppe des Servers?
/cloudserver funktioniert nur auf Servern, dessen GroupMode LOBBY oder STATIC_LOBBY ist. 
Schau da einfach mal in der Gruppendatei unter Master/groups nach.

**Comment by TheMeinerLP** [comment]
#196
