### ISSUE TITLE
Fix loading templates

### ISSUE THREAD

**Issue by GiantTreeLP** [CloudNetService/CloudNet-v2#186]
https://github.com/CloudNetService/CloudNet/blob/cb3f7a126ae76374fcb18b04273705f3565ade7f/cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java#L276-L282

@MeinerLP1 please fix this asap, due to the nature of `&`, this is not short-circuiting.

Also, `STATIC_LOBBY` servers are not handled.

**Comment by TheMeinerLP** [comment]
This bug is fixed in the pull-request #188
