### ISSUE TITLE
Rework database interface for the cloud and moduls

### ISSUE THREAD

**Issue by TheMeinerLP** [CloudNetService/CloudNet-v2#189]
Rework some api interface for cloudnet workflow

**Comment by GiantTreeLP** [comment]
I am currently testing the Nitrite database.
It is a document store, so the interface for dynamic databases experiences no changes.

**Comment by GiantTreeLP** [comment]
Success, the cloud works with this new type of database.

Next up: Converting existing databases to this database format.

**Comment by GiantTreeLP** [comment]
The converter is done. After documenting the code, it is ready to merge.

**Comment by GiantTreeLP** [comment]
Closed by d30d0d06976f2225eb58c213dedad727710b9774.
