### ISSUE TITLE
"cloudserver" command only available on lobbies

### ISSUE THREAD

**Issue by einrobin** [CloudNetService/CloudNet-v2#196]
The cloudserver command (bukkit) is only registered on servers with the group mode "LOBBY" or "STATIC_LOBBY", which was fine before 2.1.15, because there were only features that are available on lobbies, but now, there is also "/cloudserver debug", which should be available on every server. This command should be registered on every server and not only on lobbies.

**Comment by GiantTreeLP** [comment]
Fixed in https://github.com/CloudNetService/CloudNet/commit/1f272afdc1d2ef8ef11081e5eb6479f4e87dcd2a
