### ISSUE TITLE
 where can I download the CloudnetAPI for the version 2.1.17?

### ISSUE THREAD

**Issue by robincosmos** [CloudNetService/CloudNet-v2#216]
Can anyone send me a link from the cloudnetapi where I can download the CloudnetAPI

**Comment by GiantTreeLP** [comment]
You can get everything by either adding the relevant dependency to your Maven or Gradle build file (refer to https://github.com/CloudNetService/CloudNet/blob/master/README.md), downloading it from our releases (https://github.com/CloudNetService/CloudNet/releases) or from our official website (https://cloudnetservice.eu/cloudnet/version/release/).
