### ISSUE TITLE
Standard Bukkit-BroadcastMessage ghet NICHT+ Essentials Join message geht nicht?

### ISSUE THREAD

**Issue by NoobKeksTV** [CloudNetService/CloudNet-v2#23]
Mit dem neuen Update funktioniert einfach ausm nichts, ohne nderungen auf meiner seite/ meinen plugins 
der Broadcaster für mein BW system nichtmehr. Also ich sehe die NAchrhten nichtmehr im chat, in der Konsole Jedoch schon. Dasselbe bei Essentials X. 

Bedwars Server Plugins:
Mein BW (Grundgerüst von Davecrafter, teilst modifiziert wie z.b. Bei ende stop, statt rl) <- Bukkit.broadcastMessage geht nicht
Essentials system von mir (Gems, help, sowas halt.) <- FUNZT GANZ

Mehr ist dort nicht drauf.
Beispiel Source, wo es nicht geht: https://hastebin.com/axipejujen.java  (beispielhaft Zeile 56) Imports sind nur PaperSpigot 1.8.8+die CloudNetAPI (Aktuellste aus CN)

Essentials Problem Server Plugins:
http://prntscr.com/kb1ikr

Essentials config:
https://hastebin.com/nahibawapi.coffeescript

Wichtig zu sagen ist:
Beide Probleme sind NICHT da, wenn ich eine ältere Version von Cloudnet, einen Einzelnden MC server, oder einen localhost Server verwernde, was zu 99% sagt, es muss an der Cloud liegen.

**Comment by NoobKeksTV** [comment]
Ich kann jedoch nicht auf der alten version bleiben, da ich PlotSquared nutze, was sonst nicht funktioniert.

**Comment by NoobKeksTV** [comment]
Ums genau zu sagen, wie grad herausgefunden: allgemein geht kein Bukkit.Broadcastmessage ??

**Comment by Sarsum** [comment]
Bist du dir sicher, dass bei der alten Version nicht vielleicht eine andere Spigot/Paper/... Version genutzt wird und es mit der neuen/jetzigen nicht mehr geht?

**Comment by NoobKeksTV** [comment]
Ja. es wird/wurde nichts geändert außer an der Cloud Version.

**Comment by NoobKeksTV** [comment]
ansonst lass anydesk. guck. sieh selbst

**Comment by derklaro** [comment]
Hallo @ZockerBoysHD 
YOUR_MAIN_INSTANCE.getServer().broadcastMessage("test");
CloudNet überschreibt broadcastMessage() nicht, daher kann der Fehler nicht von der Cloud kommen.

**Comment by NoobKeksTV** [comment]
Dann sagst du mir Jetzt mal aber, woher das SONST kommen sollte, wenn nichts außer CloudNet verändert wird und es doch mit der alten Version Perfekt Klappt.

**Comment by derklaro** [comment]
#close

**Comment by byRoadrunner** [comment]
Closed due to inactivity
