### ISSUE TITLE
Incorrect management of errors when copying files for servers into the template

### ISSUE THREAD

**Issue by TheMeinerLP** [CloudNetService/CloudNet-v2#292]
**Description of the bug:**

Currently, the error is not output or ignored when copying servers. 
The code can be read here:
-> [Code](https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java#L600)

**Steps to reproduce this bug:**

The easiest way to reproduce the error is to make a Linux user with no rights to write and then let the server copy by command. You will notice that the content is not where it should be. But also no error comes in the wrapper

**Expected behavior:**

Actually a message should be displayed that the content/server could not be copied for several reasons

**Screenshots:**

![image](https://user-images.githubusercontent.com/6745190/86000181-79dba380-ba0d-11ea-8312-66adcd790542.png)

**Environment and used hardware:**

 System specifications: Any
 OS:  Any
 Version: Any

**Additional context (optional):**

We should output the error via logger with a separate message
```Java
catch (Exception e) {
    logger.log(Level.SERVE, "Something unexpected happened when copying the server to the template. ", e);
}
```

**Comment by GiantTreeLP** [comment]
Done in development with d91242d2b2933dd999496332aa65ad2202b0316f.
