### ISSUE TITLE
Failed to Verify Username

### ISSUE THREAD

**Issue by xLixon** [CloudNetService/CloudNet-v2#354]
Wrapper ist auf MC 1.8 installiert.
Ich erstelle einen Vanilla server, lösche alle welten und ändere die Spigot.jar zu einer 1.16.5 spigot.jar
Dann will ich auch den Server connecten und es kommt "Failed to verify username"

 - 8Cores 64GB RAM
 - OS: Debian 
 - CloudNet 2.1.17

**Comment by TheMeinerLP** [comment]
Ab java 12+ musst du eine Paper Spigot verwenden

**Comment by TheMeinerLP** [comment]
Und es wäre schön wenn du Issue Template verwenden würdest!

**Comment by xLixon** [comment]
Issue Templte wurde genutzt aber ich habe nur das rein, was ich selber gebraucht habe.
Und java is wegen Spigot 1.8 auf Java 8 (Nein hier funktioniert der spigot command nicht)

**Comment by TheMeinerLP** [comment]
Welcher Spigot Command ?

**Comment by xLixon** [comment]
Der auf dem Discord wegen Spigot 1.8 und Java 8

**Comment by TheMeinerLP** [comment]
ja der geht hier nicht, aber ab Spigot 1.12+ musst du PaperSpgiot verwenden

**Comment by xLixon** [comment]
Also 1.16.5 funktioniert nicht, nur Paper?

**Comment by TheMeinerLP** [comment]
Ja nur PaperSpigot. Aber die 1.16.5 Funktoniert

**Comment by xLixon** [comment]
Achso okey

**Comment by xLixon** [comment]
jetzt gehts
