### ISSUE TITLE
Problem mit Drittanbieter-Permissionsystem

### ISSUE THREAD

**Issue by lusu007** [CloudNetService/CloudNet-v2#68]
Hey @Dytanic ,

erstmal: Respekt! Echt super gutes System.

Ich würde gerne LuckPerms auf meinen Servern anstelle von CPerms verwenden, da dies einige Features hat, die ich benötige.
Ist dies einfach möglich?

Ich habe es nämlich mal testweise in allen Templates, die ich hab mit eingefügt. Ich habe der Gruppe Administrator `luckperms.*` Permissions gegeben und mich per Konsole zu dieser Gruppe hinzugefügt.
Jedoch kann ich nicht auf die Befehle von LuckPerms zugreifen. Dasselbe gilt für allte `/cloudserver` Befehle. Für diese habe ich die Permission `cloudnet.*` gesetzt.

Liegt das am CloudNet System oder habe ich einfach etwas falsch gemacht?

~ lusu007

**Comment by Sarsum** [comment]
Hi, 
damit ein anderes Permissionsystem funktioniert musst du in der perms.yml in Master/local/ das Permissionsystem deaktivieren und in der config.yml vom Master den Namen des Permissionsystem-Modules bei den "disabled-modules" hinzufügen!
Ich meine, dass das "CloudNet-Permission-Module" ist, du du kannst das aber einfach nach schauen da das Module im Ordner Master/modules/ liegt und dort genauso heißt (bis auf die Dateiendung, die einfach weg lassen)

Ich hoffe, dass das Problem damit behoben ist

**Comment by lusu007** [comment]
@Sarsum vielen Dank für die echt super schnelle Antwort.
Dein Vorschlag hat das Problem direkt behoben. Danke! :)

**Comment by derklaro** [comment]
@lusu007 Welche Funktionen hat denn Luk-Perms, welche in CloudNet fehlen?

**Comment by lusu007** [comment]
@KlaroYT Zum Beispiel Tracks oder Welten abhängige Permissions und MongoDB Integration.

**Comment by derklaro** [comment]
Naja, wenn ich einen BuzngeeCord Server mache, brauche ich keine Welten abhängigen Permissions

**Comment by lusu007** [comment]
@KlaroYT Natürlich, wenn du trotz des BungeeCord Netzwerkes auf einem Server mehrere Welten hast. Zum Beispiel einen Bauserver mit mehreren Maps oder einen Citybuild auf dem die Farmwelt auf dem selben Server läuft, wie die Welt mit den Grundstücken.
